version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: studyforest
      POSTGRES_PASSWORD: studyforestpw
      POSTGRES_DB: studyforest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgres://studyforest:studyforestpw@db:5432/studyforest
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always

volumes:
  db_data:
